name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'data/raw/**', 'ingest.py', 'Makefile' ]
  pull_request:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4        # get repo files :contentReference[oaicite:6]{index=6}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: make ingest
